image: node:latest

stages:
  - build
  # - test
  - deploy

build-frontend:
  stage: build
  cache:
    key:
      prefix: 'frontend'
      files:
        - 'package-lock.json'
    paths:
      - 'node_modules/'
  script:
    - npm install
    - npm run build
  only:
    refs:
      - merge_requests
    variables:
      - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "staging"
  artifacts:
    expire_in: 1 days
    when: on_success
    paths:
      - ./dist
      - ./node_modules

# build-backend:
#   stage: build
#   cache:
#     key:
#       prefix: 'backend'
#       files:
#         - 'server/package-lock.json'
#     paths:
#       - 'server/node_modules/'
#   script:
#     - cd server
#     - npm install
#   only:
#     refs:
#       - merge_requests
#     variables:
#       - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "staging"
#   artifacts:
#     expire_in: 1 days
#     when: on_success
#     paths:
#       - server/node_modules


# test:
#   stage: test
#   only:
#     refs:
#       - merge_requests
#     variables:
#       - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "staging"
#   dependencies:
#     - build-backend
#   script:
#     - cd server
#     - npm run test

deploy:
  stage: deploy
  image: mcr.microsoft.com/azure-cli
  dependencies:
    - build-frontend
  #   - build-backend
  only:
    refs:
      - merge_requests
    variables:
      # - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "staging"
      - $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_NAME == "staging"
  before_script:
    - "az login --allow-no-subscriptions --service-principal -u $AZ_SP_ID -p $AZ_SP_SECRET -t $AZ_TENANT"
  script:
    - zip -r deploy.zip dist node_modules server package.json
    - "az webapp config appsettings set --resource-group $RESOURCE_GROUP_NAME --name $APP_NAME --settings WEBSITE_RUN_FROM_PACKAGE=1"
    - "az webapp config appsettings set --resource-group $RESOURCE_GROUP_NAME --name $APP_NAME --settings ATLAS_URI=$ATLAS_URI"
    - "az webapp deployment source config-zip --resource-group $RESOURCE_GROUP_NAME --name $APP_NAME --src deploy.zip"

deploy:
  stage: deploy
  image: mcr.microsoft.com/azure-cli
  dependencies:
    - build-frontend
  #   - build-backend
  only:
    refs:
      - merge_requests
    variables:
      - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "staging"
  before_script:
    - "az login --allow-no-subscriptions --service-principal -u $AZ_SP_ID -p $AZ_SP_SECRET -t $AZ_TENANT"
  script:
    - zip -r deploy.zip dist node_modules server package.json
    - "az webapp config appsettings set --resource-group $RESOURCE_GROUP_NAME --name $APP_NAME_TESTING --settings WEBSITE_RUN_FROM_PACKAGE=1"
    - "az webapp config appsettings set --resource-group $RESOURCE_GROUP_NAME --name $APP_NAME_TESTING --settings ATLAS_URI=$ATLAS_URI"
    - "az webapp deployment source config-zip --resource-group $RESOURCE_GROUP_NAME --name $APP_NAME_TESTING --src deploy.zip"
